language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
services:
      - couchdb
# command to install dependencies
before_install:
      #    - sudo apt-get -qq update
      #    - sudo apt-get install -y gfal2* libgfal2-2 libgfal2-dev libgfal-srm-ifce1
      #    - pip install gfal2-python 
    - apt-get install globus-gass-copy-progs voms-clients
    - add-apt-repository 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core'
    - apt-get update
    - apt-get install ca-policy-egi-core
    - pip install pyyaml
script:
  - nosetests
# # command to run tests
