language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
    #  - "3.7"
services:
      - couchdb
# command to install dependencies
before_install:
      #    - sudo apt-get -qq update
      #    - sudo apt-get install -y gfal2* libgfal2-2 libgfal2-dev libgfal-srm-ifce1
      #    - pip install gfal2-python 
      #    - sudo apt-get install globus-gass-copy-progs voms-clients -y
      #    - sudo add-apt-repository -y 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core' 
      #    - sudo apt-get update 
      #    - sudo mkdir -p /etc/grid-security/certificates/
      #    - sudo apt-get -y --allow-unauthenticated install ca-policy-egi-core 
    - pip install mock
    - pip install codecov
    - curl -X PUT localhost:5984/test_db

script:
    - nosetests --with-coverage

after_success:
  - codecov

# # command to run tests
