language: python
#dist: xenial
#sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
    #  - "3.7"
services:
      - couchdb
# command to install dependencies
before_install:
    - sudo apt-get update
    - sudo apt-get install libdpm-dev libboost-all-dev python-dev libglibmm-2.4-1c2a
    - sudo apt-get install -y dpkg
    - wget http://mirrors.kernel.org/ubuntu/pool/main/j/json-c/libjson-c3_0.12.1-1.3_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal-transfer2_2.13.4-1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/gfal2_2.15.2-1_all.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal2-2_2.13.4-1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/attr/libattr1_2.4.47-2build1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/main/a/attr/libattr1-dev_2.4.47-2build1_amd64.deb
    - wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gfal2/libgfal2-dev_2.13.4-1_amd64.deb
      #    - wget http://security.ubuntu.com/ubuntu/pool/main/g/gcc-7/libstdc++6_7.2.0-8ubuntu3.2_amd64.deb
      #    - sudo dpkg --install libstdc++6_7.2.0-8ubuntu3.2_amd64.deb
    - sudo apt-get install -y gcc-7
    - sudo dpkg --install libjson-c3_0.12.1-1.3_amd64.deb 
    - sudo dpkg --install libgfal2-2_2.13.4-1_amd64.deb
    - sudo dpkg --install libgfal-transfer2_2.13.4-1_amd64.deb
    - sudo dpkg --install gfal2_2.15.2-1_all.deb
    - sudo dpkg --install libattr1_2.4.47-2build1_amd64.deb 
    - sudo dpkg --install libattr1-dev_2.4.47-2build1_amd64.deb 
    - sudo dpkg --install libgfal2-dev_2.13.4-1_amd64.deb
    - pip install  git+https://github.com/cern-fts/gfal2-python.git@v1.9.3
      #    - sudo apt-get install globus-gass-copy-progs voms-clients -y
      #    - sudo add-apt-repository -y 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core' 
      #    - sudo apt-get update 
      #    - sudo mkdir -p /etc/grid-security/certificates/
      #    - sudo apt-get -y --allow-unauthenticated install ca-policy-egi-core 
    - pip install mock
      #    - wget http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo_latest_all.deb
      #    - dpkg -i globus-toolkit-repo_latest_all.deb
      #    - apt-get install globus-data-management-client
    - pip install codecov
    - curl -X PUT localhost:5984/test_db

script:
    - nosetests --with-coverage

after_success:
  - codecov

# # command to run tests
