language: python
#dist: xenial
#sudo: required
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
    #  - "3.7"
services:
      - couchdb
# command to install dependencies
before_install:
    -  sudo apt-get update
    -  sudo echo "deb http://cz.archive.ubuntu.com/ubuntu artful main universe" >> /etc/apt/sources.list
    -  sudo apt-get update
    -  sudo apt-get install gfal2 libgfal2-dev libgfal2-2  libboost-all-dev python-dev gfal2-doc gfal2-plugin-* libdpm-dev libgfal-transfer2 libgfal-srm-ifce1 gfal2-dbg
    -  pip install  git+https://github.com/cern-fts/gfal2-python.git@v1.9.3

      #    - sudo apt-get install globus-gass-copy-progs voms-clients -y
      #    - sudo add-apt-repository -y 'deb http://repository.egi.eu/sw/production/cas/1/current egi-igtf core' 
      #    - sudo apt-get update 
      #    - sudo mkdir -p /etc/grid-security/certificates/
      #    - sudo apt-get -y --allow-unauthenticated install ca-policy-egi-core 
    - pip install mock
    - wget http://www.globus.org/ftppub/gt6/installers/repo/globus-toolkit-repo_latest_all.deb
    - dkg -i globus-toolkit-repo_latest_all.deb
    - apt-get install globus-data-management-client
    - pip install codecov
    - curl -X PUT localhost:5984/test_db

script:
    - nosetests --with-coverage

after_success:
  - codecov

# # command to run tests
